apiVersion: ocm.software/v3alpha1
kind: ComponentVersion
metadata:
  name: github.com/sidhishruti22/backendtest
  provider:
    name: sidhishruti22
  version: v1.0.1
repositoryContexts: []
spec:
  resources:
  - access:
      localReference: sha256.a7dd532f80e8417ed33cf0c97328582847017895fc5146e499bdf4c94a9d17b5
      mediaType: application/yaml
      type: localBlob
    name: config
    relation: local
    type: configdata.ocm.software
    version: v1.0.1
  - access:
      imageReference: ghcr.io/stefanprodan/podinfo:6.3.3
      type: ociArtifact
    name: image
    relation: external
    type: ociImage
    version: 6.2.1
  - access:
      localReference: sha256.fa26e176cd01db747a1659814d13f446fc6313c3405094537e384bc1db0868e0
      mediaType: application/x-tgz
      type: localBlob
    name: manifests
    relation: local
    type: kustomize.ocm.fluxcd.io
    version: v1.0.1
