apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentVersion
metadata:
  name: podifytest
  namespace: ocm-system
spec:
  interval: 10m0s
  component: github.com/sidhishruti22/podifytest
  version:
    semver: "=>v1.0.1"
  repository:
    url: ghcr.io/sidhishruti22
    secretRef:
      name: creds
  references:
    expand: true
  

