apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentVersion
metadata:
  name: podify_test
  namespace: ocm-system
spec:
  interval: 10m0s
  component: github.com/sidhishruti22/podify_test
  version:
    semver: "=>v1.0.1"
  repository:
    url: ghcr.io/sidhishruti22
    secretRef:
      name: creds
  references:
    expand: true
  verify:
  - name: key
    publicKey:
      secretRef:
        name: publickey  

